### ISSUE TITLE
Bitmap ends up as non-fixnum on 32-bit LispWorks

### ISSUE THREAD

**Issue by Yehouda** [DanielKeogh/hashtrie#1]
https://github.com/DanielKeogh/hashtrie/blob/c39e81f91ffcc3d66bd0daa1330d3a50f3ac0dbe/utils.lisp#L8

The code seems to rely on an integer with  **+size+** bits being a fixnum, which is not true on LispWorks 32 bits (and presumably other 32 bit Lisps). 

When running the tests, it first goes wrong inside **hman-pack**, when _i_ is biger than 29: 
https://github.com/DanielKeogh/hashtrie/blob/c39e81f91ffcc3d66bd0daa1330d3a50f3ac0dbe/hashtrie.lisp#L411

because of the aggressive declarations of safety 0, it normally errors sometime later and also cause (a little) memory corruption. 

One option is to make the whole package 64 bit only. trivial-features pushes **:64bits** or **:32-bits** on features, so you can use that for checking. 

 Otherwise it needs to be more careful. The eay to find the maximum number of bits in a fixnum is to use `(integer-length most-positive-fixnum)`,  So you can define**+size+** to  the biggest power of 2 below it (and also define **+bits+** accordingly).

**Comment by DanielKeogh** [comment]
It's probably worth factoring this to use 30 bits rather than 32. I only recently learned that fixnum in CL was missing 2 bits.

**Comment by Yehouda** [comment]
**Fixnum** is signed, so the 30 bits contain a sign bit, and you can use only 29 bits (0 - 28 inclusive). `(ash 1 29)` is a bignum.

**Comment by DanielKeogh** [comment]
Should work on 32 bit lisps now. Thanks for the bug report.

**Comment by DanielKeogh** [comment]
And thanks to your prompting and some things I've learned recently, my benchmark in sbcl now shows that this is going faster than the clojure equivalent: 

```lisp
(time (length (with-transient (trans (make-hashtrie))
			  (dotimes (i 1000000)
			    (add trans i i)))))
		
Evaluation took:
  0.411 seconds of real time
  0.529386 seconds of total run time (0.529386 user, 0.000000 system)
  [ Real times consist of 0.055 seconds GC time, and 0.356 seconds non-GC time. ]
  [ Run times consist of 0.172 seconds GC time, and 0.358 seconds non-GC time. ]
  128.71% CPU
  56 lambdas converted
  824,797,560 processor cycles
  213,208,704 bytes consed
```
