### ISSUE TITLE
Shouldn't do proclaim (optimize at top level

### ISSUE THREAD

**Issue by Yehouda** [DanielKeogh/hashtrie#2]
https://github.com/DanielKeogh/hashtrie/blob/c39e81f91ffcc3d66bd0daa1330d3a50f3ac0dbe/api.lisp#L5

This line means that after loading this file, any code that is compiled in the same same process is compiled with these optimizations. 

To limie it to this file. it should be surrounded by [(eval-when (:compile-toplevel)**.. )](https://www.lispworks.com/documentation/lw70/CLHS/Body/s_eval_w.htm):

```
(eval-when (:compile-toplevel)
    (proclaim '(optimize (speed 3) (safety 0) (debug 0))) )
```

BTW: since this file is the interface, it should really be compiled with high safety, to catch user errors (e.g. wrong number of arguments), and maybe high debug level too, to make it easier to debug code that uses it.

**Comment by DanielKeogh** [comment]
I've removed this as per your advice.
